spring.application.name=cache

spring.cache.jcache.config=classpath:ehcache.xml

server.port= 8081
# Data Base
spring.h2.console.enabled = true
spring.datasource.url=jdbc:h2:mem:test

spring.jpa.hibernate.ddl.auto=create-drop
#spring.jpa.hibernate.ddl.auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# Redis Server Configuration
spring.redis.host=localhost
spring.redis.port=6379
#spring.redis.password=your_password_here    # (Optional, if Redis is password protected)

# Connection Pool Configuration (Lettuce)
#spring.redis.lettuce.pool.max-active=8
#spring.redis.lettuce.pool.max-idle=8
#spring.redis.lettuce.pool.min-idle=0
#spring.redis.lettuce.pool.max-wait=PT2S   # Max wait time for a connection (ISO-8601 duration format)

# Timeout Settings
#spring.redis.timeout=5000ms   # Connection timeout


# Cache Settings (Optional)
spring.cache.type=redis
spring.cache.redis.time-to-live = 60000ms
spring.cache.redis.cache-null-values =false
#spring.cache.redis.use-key-prefix = true
#spring.cache.redis.key-prefix = library